sudo: required
services:
- docker
script:
- docker build -t ausnimbus/openshift-letsencrypt:latest .
notifications:
  slack:
    secure: pR+r8EhKUmlCj6vAMxlvy1SmnNt09ALkTnDXGHggPofbwWZpEN9X5QpdgLBgRsgtf6X7WCTp6QGCyUyFEkJonpEHt4aTgN/85PYCL0pyGQnR/z7s6S4XkGwO56cNxdgM82oBVHb/5sWnjPr/GOnvLy2/inOPdST0vbqN/YTY8No0xaAyzJG5vhhLM9ECYS5SNDXG72bofNiey61U3kJAINkRdXeoJV3jAblJgUd90z+ZsttlBx1rlJQPS1efbX0oMcaeMJWSXhvphfcyOn4cWK8nHJRrR55WEUmUsUBCnrJNNz6pB8kNWUGKr4g0jrn0AYmx232Gm8YW5ot1L0Ic27JAZoQ8thRWmFzXi+bKbr07ypd0QcPwQIeLEQC8jj82YXzBg9MzYLIdnfe+mfAVQhqfJU9HnV+RIvROECgFClkGdcBOa+W2tJ8XkvRu9NBFcybL+LatI3y9Z8Oi0bVGbmfL8bi6W5DWyO79ssyBWaIe72pOYeBU1MiLvIurQ9REtPDlIt7O5gcqpIaOjukxxRQsbCNGzOxwUhdBSvgW2mGwsMp/x1oKEcXXSof5wOIZujws+vfgKDYIoKHJbha2Y9BHCcQ67v03m/LqSNIusShr5VwIr4VxWCbR61DoXp6UJ6nGxAdNdOk0scKNGpQVyWhKFLqPYDh2scvXPXvITKU=
